In [2]:
# 우리는 마트의 데이터분석가이다. 데이터분석 요청을 받았다.
# 어느 것을 팔때 번들로 판매하는 것이 좋을지 확인하는 것
# 유통과정에서 문제가 될 수 있는 경우 대체제를 찾거나 보완재를 찾는 것을 요구하였다. 
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

dataset = [['Milk', 'Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Onion', 'Nutmeg', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Ice cream', 'Eggs']]

In [3]:
te = TransactionEncoder()

In [16]:
df.columns

Index(['Apple', 'Corn', 'Eggs', 'Ice cream', 'Milk', 'Nutmeg', 'Onion',
       'Unicorn', 'Yogurt'],
      dtype='object')

In [5]:
te_ary = te.fit(dataset).transform(dataset)
df=pd.DataFrame(te_ary, columns=te.columns_)
df

   Apple   Corn   Eggs  Ice cream   Milk  Nutmeg  Onion  Unicorn  Yogurt
0  False  False   True      False   True    True   True    False    True
1  False  False   True      False  False    True   True    False    True
2   True  False   True      False   True   False  False    False   False
3  False   True  False      False   True   False  False     True    True
4  False   True   True       True  False   False   True    False   False

In [12]:
apriori(df,min_support=0.4,use_colnames=True)

    support                       itemsets
0       0.4                         (Corn)
1       0.8                         (Eggs)
2       0.6                         (Milk)
3       0.4                       (Nutmeg)
4       0.6                        (Onion)
5       0.6                       (Yogurt)
6       0.4                   (Milk, Eggs)
7       0.4                 (Nutmeg, Eggs)
8       0.6                  (Onion, Eggs)
9       0.4                 (Eggs, Yogurt)
10      0.4                 (Milk, Yogurt)
11      0.4                (Onion, Nutmeg)
12      0.4               (Nutmeg, Yogurt)
13      0.4                (Onion, Yogurt)
14      0.4          (Onion, Nutmeg, Eggs)
15      0.4         (Eggs, Nutmeg, Yogurt)
16      0.4          (Eggs, Onion, Yogurt)
17      0.4        (Onion, Nutmeg, Yogurt)
18      0.4  (Eggs, Onion, Nutmeg, Yogurt)

In [13]:
freq_itemsets = apriori(df,min_support=0.4,use_colnames=True)
freq_itemsets

    support                       itemsets
0       0.4                         (Corn)
1       0.8                         (Eggs)
2       0.6                         (Milk)
3       0.4                       (Nutmeg)
4       0.6                        (Onion)
5       0.6                       (Yogurt)
6       0.4                   (Milk, Eggs)
7       0.4                 (Nutmeg, Eggs)
8       0.6                  (Onion, Eggs)
9       0.4                 (Eggs, Yogurt)
10      0.4                 (Milk, Yogurt)
11      0.4                (Onion, Nutmeg)
12      0.4               (Nutmeg, Yogurt)
13      0.4                (Onion, Yogurt)
14      0.4          (Onion, Nutmeg, Eggs)
15      0.4         (Eggs, Nutmeg, Yogurt)
16      0.4          (Eggs, Onion, Yogurt)
17      0.4        (Onion, Nutmeg, Yogurt)
18      0.4  (Eggs, Onion, Nutmeg, Yogurt)

In [14]:
association_rules(freq_itemsets)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(Nutmeg),(Eggs),0.4,0.8,0.4,1.0,1.250000,0.08,inf,0.333333
1,(Onion),(Eggs),0.6,0.8,0.6,1.0,1.250000,0.12,inf,0.500000
2,(Nutmeg),(Onion),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
3,(Nutmeg),(Yogurt),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
4,"(Onion, Nutmeg)",(Eggs),0.4,0.8,0.4,1.0,1.250000,0.08,inf,0.333333
5,"(Eggs, Nutmeg)",(Onion),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
6,(Nutmeg),"(Onion, Eggs)",0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
7,"(Nutmeg, Eggs)",(Yogurt),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
8,"(Yogurt, Eggs)",(Nutmeg),0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
9,"(Yogurt, Nutmeg)",(Eggs),0.4,0.8,0.4,1.0,1.250000,0.08,inf,0.333333
10,(Nutmeg),"(Yogurt, Eggs)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
11,"(Yogurt, Eggs)",(Onion),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
12,"(Onion, Yogurt)",(Eggs),0.4,0.8,0.4,1.0,1.250000,0.08,inf,0.333333
13,"(Onion, Nutmeg)",(Yogurt),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
14,"(Onion, Yogurt)",(Nutmeg),0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
15,"(Yogurt, Nutmeg)",(Onion),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
16,(Nutmeg),"(Onion, Yogurt)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
17,"(Nutmeg, Onion, Eggs)",(Yogurt),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
18,"(Yogurt, Onion, Eggs)",(Nutmeg),0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
19,"(Yogurt, Nutmeg, Eggs)",(Onion),0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
20,"(Yogurt, Onion, Nutmeg)",(Eggs),0.4,0.8,0.4,1.0,1.250000,0.08,inf,0.333333
21,"(Nutmeg, Eggs)","(Onion, Yogurt)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
22,"(Yogurt, Eggs)","(Onion, Nutmeg)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
23,"(Onion, Nutmeg)","(Yogurt, Eggs)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
24,"(Onion, Yogurt)","(Nutmeg, Eggs)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000
25,"(Yogurt, Nutmeg)","(Onion, Eggs)",0.4,0.6,0.4,1.0,1.666667,0.16,inf,0.666667
26,(Nutmeg),"(Yogurt, Onion, Eggs)",0.4,0.4,0.4,1.0,2.500000,0.24,inf,1.000000

In [15]:
res = association_rules(freq_itemsets,metric='lift')
res[res['lift']>1.5]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
10,(Onion),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
11,(Nutmeg),(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
12,(Nutmeg),(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
13,(Yogurt),(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
17,"(Onion, Eggs)",(Nutmeg),0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
18,"(Eggs, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
19,(Onion),"(Eggs, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
20,(Nutmeg),"(Onion, Eggs)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
22,"(Nutmeg, Eggs)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
23,"(Yogurt, Eggs)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
26,(Nutmeg),"(Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
27,(Yogurt),"(Nutmeg, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
29,"(Yogurt, Eggs)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
32,(Onion),"(Yogurt, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
34,"(Onion, Nutmeg)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
35,"(Onion, Yogurt)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
36,"(Yogurt, Nutmeg)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
37,(Onion),"(Yogurt, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
38,(Nutmeg),"(Onion, Yogurt)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
39,(Yogurt),"(Onion, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
40,"(Nutmeg, Onion, Eggs)",(Yogurt),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
41,"(Yogurt, Onion, Eggs)",(Nutmeg),0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
42,"(Yogurt, Nutmeg, Eggs)",(Onion),0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
44,"(Onion, Eggs)","(Yogurt, Nutmeg)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
45,"(Nutmeg, Eggs)","(Onion, Yogurt)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
46,"(Yogurt, Eggs)","(Onion, Nutmeg)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
47,"(Onion, Nutmeg)","(Yogurt, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
48,"(Onion, Yogurt)","(Nutmeg, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
49,"(Yogurt, Nutmeg)","(Onion, Eggs)",0.4,0.6,0.4,1.000000,1.666667,0.16,inf,0.666667
51,(Onion),"(Yogurt, Nutmeg, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000
52,(Nutmeg),"(Yogurt, Onion, Eggs)",0.4,0.4,0.4,1.000000,2.500000,0.24,inf,1.000000
53,(Yogurt),"(Nutmeg, Onion, Eggs)",0.6,0.4,0.4,0.666667,1.666667,0.16,1.8,1.000000